name: my-first-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test
        uses: actions/setup-node@v3
        with:
          node-version: "24.11.0"

      - name: Build and Test
        run: |
          cd node-ci-cd
          npm --version
          node --version
          npm install

  deploy-image:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_IMAGE: suryabhaskarvempala/ultimate-cicd:${{ github.run_number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd node-ci-cd
          docker build -t suryabhaskarvempala/ultimate-cicd:${{ github.run_number }} .
          docker push suryabhaskarvempala/ultimate-cicd:${{ github.run_number }}

  update-gitops-repo:
    runs-on: ubuntu-latest
    needs: deploy-image
    env:
      GIT_REPO_NAME: Ultimate-GitOps
      GIT_USER_NAME: VempalaSuryaBhaskar
      GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Update GitOps Repository
        run: |

          echo "Cleaning old GitOps repository..."
          rm -rf gitops

          echo "Cloning GitOps repository..."

          git clone https://${GITHUB_TOKEN}@github.com/VempalaSuryaBhaskar/Ultimate-GitOps.git gitops

          cd gitops

          echo "Configuring Git..."
          git config user.email "vempalasvdbhaskar@gmail.com"
          git config user.name "VempalaSuryaBhaskar"

          echo "Updating deployment image..."

          sed -i -E "s#suryabhaskarvempala/ultimate-cicd:(replaceImageTag|[0-9]+)#suryabhaskarvempala/ultimate-cicd:${IMAGE_TAG}#g" manifests/deployment.yml

          echo "Updated deployment:"
          cat manifests/deployment.yml

          echo "Git diff:"
          git diff

          echo "Adding deployment file..."
          git add manifests/deployment.yml

          echo "Committing changes..."
          git commit -m "Git hub Actions Commit" || echo "No changes to commit"

          echo "Pushing changes..."
          git push origin main

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: update-gitops-repo

    env:
      IMAGE_TAG: ${{ github.run_number }}
      DOCKER_IMAGE: suryabhaskarvempala/ultimate-cicd:${{ github.run_number }}

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2"

            echo "Checking Docker..."

            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."

              sudo apt-get update
              sudo apt-get install -y docker.io

              sudo systemctl enable docker
              sudo systemctl start docker
            else
              echo "Docker already installed"
            fi

            echo "Docker version:"
            docker --version

            echo "Pulling image:"
            echo "${DOCKER_IMAGE}"

            sudo docker pull ${DOCKER_IMAGE}

            echo "Stopping old container..."

            sudo docker stop node-app || true

            echo "Removing old container..."

            sudo docker rm node-app || true

            echo "Starting new container..."

            sudo docker run -d \
              --name node-app \
              -p 8080:8080 \
              ${DOCKER_IMAGE}

            echo "Deployment completed"

            echo "Running containers:"

            sudo docker ps

  notify:
    runs-on: ubuntu-latest

    needs:
      - build
      - deploy-image
      - update-gitops-repo
      - deploy-ec2

    if: ${{ always() && contains(needs.*.result, 'failure') }}

    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: "🚨 CI/CD Pipeline Failed - Ultimate CICD"

          to: suryabhaskarvempala@gmail.com
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>

          body: |
            Hello Surya,

            The GitHub Actions CI/CD pipeline has FAILED.

            Repository:
            ${{ github.repository }}

            Branch:
            ${{ github.ref_name }}

            Commit:
            ${{ github.sha }}

            Workflow:
            ${{ github.workflow }}

            Run Number:
            ${{ github.run_number }}

            Please open the GitHub Actions workflow run and check which stage failed.

            GitHub Actions:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,
            GitHub Actions CI/CD
